import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import NavMenu from "./NavMenu/NavMenu";
import { Providers } from "./providers";
import Footer from "./Footer/Footer";
import Header from '../app/Header/Header'

import { Lato } from 'next/font/google'

const lato = Lato({
  subsets:["latin"],
  variable: "--font-lato",
  weight: "400"
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={`${lato.variable} ${geistMono.variable} flex flex-col antialiased bg-[#FAF3E1] text-black min-h-screen`}>
        <Providers>
          {/* <NavMenu /> */}
          <Header />
          <main className="grow lg:px-10">
            {/* Load Font Awesome after page is interactive */}
            <Script
              src="https://kit.fontawesome.com/2db28a8488.js"
              crossOrigin="anonymous"
              strategy="afterInteractive"
            />
              {children}
          </main>
        </Providers>
        <div className=""><Footer /></div>
      </body>
    </html>
  );
}
