import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { Providers } from "./providers";
import Footer from "./Footer/Footer";
import Header from '../app/Header/Header'
import LandingSpinner from '../Utils/LoadingSpinner'
import { Lato } from 'next/font/google'
import PageWrapper from "@/PageWrapper/PageWrapper";
import { Suspense } from "react";
import { AuthProvider } from '../context/AuthContext';
import { GoogleOAuthProvider } from '@react-oauth/google';


const lato = Lato({
  subsets:["latin"],
  variable: "--font-lato",
  weight: "400"
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={`${lato.variable} ${geistMono.variable} flex flex-col antialiased bg-gray-100 text-black min-h-screen`}>
        <Providers>
          {/* <NavMenu /> */}
          <Header />
          <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ''}>
          <AuthProvider>
          <PageWrapper>
            <main className="">
              {/* Load Font Awesome after page is interactive */}
              <Script
                src="https://kit.fontawesome.com/2db28a8488.js"
                crossOrigin="anonymous"
                strategy="afterInteractive"
              />
              <script src="https://accounts.google.com/gsi/client" async></script>
                  {children}
            </main>
          </PageWrapper>
          </AuthProvider>
          </GoogleOAuthProvider>
        </Providers>
        <div className=""><Footer /></div>
      </body>
    </html>
  );
}
